"""models.py — Typed dataclasses used across the ADF Cost Optimizer.

These classes model activities, pipelines, factories, triggers and the final
report payload that gets passed between analysis, AI and report generation
steps.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from datetime import datetime

@dataclass
class ActivityRecord:
    # Represents a single activity's aggregated run metrics and cost
    activity_name: str
    activity_type: str
    pipeline_name: str
    factory_name: str
    environment: str
    subscription_id: str
    run_count: int = 0
    total_duration_sec: float = 0.0
    diu_hours: float = 0.0
    estimated_cost_usd: float = 0.0
    actual_cost_usd: float = 0.0
    avg_cost_per_run: float = 0.0
    actual_avg_cost_per_run: float = 0.0
    avg_duration_sec: float = 0.0
    compute_hours: float = 0.0
    data_details: Dict[str, Any] = field(default_factory=dict)
    activity_runs: List[Dict[str, Any]] = field(default_factory=list)
    definition: Dict[str, Any] = field(default_factory=dict)

@dataclass
class PipelineRecord:
    # Pipeline-level aggregated metrics and activity list
    pipeline_name: str
    factory_name: str
    environment: str
    subscription_id: str
    resource_group: str
    run_count: int = 0
    total_duration_sec: float = 0.0
    estimated_cost_usd: float = 0.0
    actual_cost_usd: float = 0.0
    avg_cost_per_run: float = 0.0
    actual_avg_cost_per_run: float = 0.0
    avg_duration_sec: float = 0.0
    last_run_end: Optional[datetime] = None
    failed_run_count: int = 0
    last_run_status: str = ""
    cost_tier: str = "low"
    activities: List[ActivityRecord] = field(default_factory=list)
    run_costs: List[Dict[str, Any]] = field(default_factory=list)
    definition: Dict[str, Any] = field(default_factory=dict)

@dataclass
class FactoryRecord:
    # Factory-level summary: contains child pipelines and counts
    factory_name: str
    factory_id: str
    resource_group: str
    subscription_id: str
    location: str
    environment: str
    estimated_cost_usd: float = 0.0
    pipeline_count: int = 0
    trigger_count: int = 0
    enabled_trigger_count: int = 0
    pipelines: List[PipelineRecord] = field(default_factory=list)

@dataclass
class TriggerRecord:
    # Trigger metadata for reporting trigger status and scheduling
    trigger_name: str
    factory_name: str
    environment: str
    subscription_id: str
    resource_group: str
    trigger_type: str
    status: str
    is_enabled: bool = False
    schedule_expression: str = ""
    pipelines_triggered: List[str] = field(default_factory=list)
    last_triggered: Optional[datetime] = None

@dataclass
class OptimizationSuggestion:
    # Represents a single recommendation generated by GenAI or rules
    pipeline_name: str
    factory_name: str
    environment: str
    current_cost_usd: float
    issue_category: str
    issue_description: str
    suggestion: str
    estimated_saving_pct: float = 0.0
    estimated_saving_usd: float = 0.0
    priority: str = "Medium"
    effort: str = "Medium"
    optimized_code_snippet: str = ""

@dataclass
class ReportPayload:
    # Top-level payload passed between steps and into the report generator
    generated_at: datetime
    date_range_days: int
    factories: List[FactoryRecord] = field(default_factory=list)
    triggers: List[TriggerRecord] = field(default_factory=list)
    optimization_suggestions: List[OptimizationSuggestion] = field(default_factory=list)
    total_cost_usd: float = 0.0
    cost_by_environment: Dict[str, float] = field(default_factory=dict)
    cost_by_factory: Dict[str, float] = field(default_factory=dict)
    analysis_start_date: Optional[datetime] = None
    analysis_end_date: Optional[datetime] = None
    selected_environments: List[str] = field(default_factory=list)
    selected_scope: Dict[str, Dict[str, List[str]]] = field(default_factory=dict)
    forecast_months: List[Dict[str, Any]] = field(default_factory=list)
    forecast_monthly_average_usd: float = 0.0
    forecast_total_6_months_usd: float = 0.0
